// Mapping between mexicanStates object keys and SVG element IDs in mx.svg
const stateIdMapping = {
    "Aguascalientes": "MXAGU",
    "Baja California": "MXBCN",
    "Baja California Sur": "MXBCS",
    "Campeche": "MXCAM",
    "Chiapas": "MXCHP",
    "Chihuahua": "MXCHH",
    "Ciudad de México": "MXCMX",
    "Coahuila de Zaragoza": "MXCOA",
    "Colima": "MXCOL",
    "Durango": "MXDUR",
    "Guanajuato": "MXGUA",
    "Guerrero": "MXGRO",
    "Hidalgo": "MXHID",
    "Jalisco": "MXJAL",
    "México": "MXMEX",
    "Michoacán de Ocampo": "MXMIC",
    "Morelos": "MXMOR",
    "Nayarit": "MXNAY",
    "Nuevo León": "MXNLE",
    "Oaxaca": "MXOAX",
    "Puebla": "MXPUE",
    "Querétaro": "MXQUE",
    "Quintana Roo": "MXROO",
    "San Luis Potosí": "MXSLP",
    "Sinaloa": "MXSIN",
    "Sonora": "MXSON",
    "Tabasco": "MXTAB",
    "Tamaulipas": "MXTAM",
    "Tlaxcala": "MXTLA",
    "Veracruz de Ignacio de la Llave": "MXVER",
    "Yucatán": "MXYUC",
    "Zacatecas": "MXZAC"
};